title: harry4455 blog
author: harry4455
email: xoxolittlemonster4455@gmail.com
description: Software Engineer
show_excerpts: true

sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: harry4455
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  social_links:
    github: harry4455
    linkedIn: in/chpark02

plugins:
  - jekyll-seo-tag
